version: '3.2'
services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 9888:9888
    volumes:
      - type: bind
        source: ./src/main/resources
        target: /policies
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--log-level=debug"
      - "--set=decision_logs.console=true"
      - "/policies"